### ISSUE TITLE
Weapons

### ISSUE THREAD

**Issue by SilvNobelen** [istoking/esx_blackmarket#1]
the resource works! But when i add an weapon, i get it as item, i can`t use it.
![image](https://user-images.githubusercontent.com/60759015/93573880-fab89480-f997-11ea-9ca8-612f25948e2d.png)

**Comment by istoking** [comment]
Yes, the way this was written was to make the items in the blackmarket items. If your inventory handles these differently, unfortunately the resource won't work as intended.
